const mongoose=require("mongoose");
const Schema=mongoose.Schema;
const Firmschema=new Schema({
    firmName:{
        type:String,
        required:true,
        unique:true
    },
    area:{
        type:String,
        required:true
    },
    category:{
        type:[
            {
                type:String,
                enum:["veg","non-veg"]
            }
        ]
    },
    region:[
        {
            type:String,
            enum:["south-indian","north-indian","chineese","Bakery"]
        }
    ],
    offer:{
        type:String
    },
    image:{
        type:String
    },
    vendor:[
    {
        type:mongoose.Schema.Types.ObjectId,
        ref:"user"
    }
    ],
    products:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"product"
        }]
})
module.exports=mongoose.model("firm",Firmschema);
